stages:
    - build
    - package
    - deploy

variables: 
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository 
  
cache: 
  paths: 
    - ./Backend/.m2/repository 
    - ./BackEnd/target

backend_build_job: 
  stage: build
  image: maven:3.8.6-openjdk-18-slim
  script:
    - cd ./BackEnd
    - echo "Maven compile started"
    - pwd
    - "mvn compile"
    - ls -lrta

backend_package_job: 
  stage: package
  image: maven:3.8.6-openjdk-18-slim 
  artifacts: 
    paths: 
     - ./BackEnd/target/wesped.jar
     
  script: 
     - cd ./BackEnd
     - pwd
     - "mvn package"
     - ls -lrta

backend_deploy: 
  stage: deploy 
  image: alpine:3.11 
  before_script: 
      - apk update && apk add openssh-client bash 
      - mkdir -p ~/.ssh 
      - eval $(ssh-agent -s) 
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null 
      - touch ~/.ssh/config 
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config 
      - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts 
  script:
      - ssh ubuntu@$DEPLOY_SERVER_IP "sudo apt install openjdk-18-jdk -y" 
      - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop wesped.service"
      - ls -lrta
      - scp ./BackEnd/target/wesped.jar ubuntu@$DEPLOY_SERVER_IP:~/wesped/ 
      - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start wesped.service"