stages:
    - build
    - deploy

backend_build_job: 
  stage: build
  image: maven:3.8.6-openjdk-18-slim
  script:
    - cd ./BackEnd
    - echo "Maven compile started"
    - mvn clean install
  artifacts:
    paths:
      - BackEnd/target/wesped.jar

backend_deploy_job: 
  stage: deploy 
  image: alpine:3.11 
  before_script: 
      - apk update && apk add openssh-client bash 
      - mkdir -p ~/.ssh 
      - eval $(ssh-agent -s) 
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null 
      - touch ~/.ssh/config 
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config 
      - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts 
  script:
      - ssh ubuntu@$DEPLOY_SERVER_IP "sudo apt install openjdk-18-jdk -y" 
      - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop wesped.service"
      - scp wesped.jar ubuntu@$DEPLOY_SERVER_IP:~/wesped/ 
      - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start wesped.service"